### ISSUE TITLE
Doesn't work with cypress 4.0.0

### ISSUE THREAD

**Issue by fr0** [flotwig/cypress-log-to-output#9]
```
2020-02-06 17:45:21 |  args.find is not a function
2020-02-06 17:45:21 |  TypeError: args.find is not a function
2020-02-06 17:45:21 |      at ensureRdpPort (/home/jenkins/workspace/atlas-dev-tools_crfrolik_bs-diff/node_modules/cypress-log-to-output/src/log-to-output.js:93:25)
2020-02-06 17:45:21 |      at Object.browserLaunchHandler [as handler] (/home/jenkins/workspace/atlas-dev-tools_crfrolik_bs-diff/node_modules/cypress-log-to-output/src/log-to-output.js:111:15)
2020-02-06 17:45:21 |      at invoke (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:25:16)
2020-02-06 17:45:21 |      at /home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/util.js:48:16
2020-02-06 17:45:21 |      at tryCatcher (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
2020-02-06 17:45:21 |      at Function.Promise.attempt.Promise.try (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
2020-02-06 17:45:21 |      at Object.wrapChildPromise (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/util.js:47:28)
2020-02-06 17:45:21 |      at execute (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:134:12)
2020-02-06 17:45:21 |      at EventEmitter.<anonymous> (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:201:5)
2020-02-06 17:45:21 |      at EventEmitter.emit (events.js:200:13)
2020-02-06 17:45:21 |      at process.<anonymous> (/home/jenkins/.cache/Cypress/4.0.0/Cypress/resources/app/packages/server/lib/plugins/util.js:25:29)
2020-02-06 17:45:21 |      at process.emit (events.js:200:13)
2020-02-06 17:45:21 |      at emit (internal/child_process.js:876:12)
2020-02-06 17:45:21 |      at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by ttomaszewski** [comment]
+1

**Comment by ldeveber** [comment]
+1

**Comment by flotwig** [comment]
Fixed in 1.0.8.
